// RTSSP Server configuration
// Port to listen for incoming Box connections
port=8888
// Directory where movie .dat files are stored
moviesdir=movies/
// Shared crypto configuration file
cryptoconfig=cryptoconfig.conf
